# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Capstone Test' do
pod 'RealmSwift'
end

target 'Capstone TestTests' do
pod 'RealmSwift'
end

target 'Capstone TestUITests' do

end

