# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'RovisysData' do
pod 'RealmSwift'
end

target 'RovisysDataTests' do
pod 'RealmSwift'
end

target 'RovisysDataUITests' do

end

